#!/usr/bin/env bash
# set -e

# SECRETS_PAYLOAD=$(kamal secrets fetch --adapter aws_secrets_manager --account account-profile-name secret-name)

# DB_HOST=$(kamal secrets extract DB_HOST $SECRETS_PAYLOAD)
# SECRET_KEY=$(kamal secrets extract SECRET_KEY $SECRETS_PAYLOAD)