#!/usr/bin/env bash
# set -e

# SECRETS_PAYLOAD=$(kamal secrets fetch --adapter aws_secrets_manager --account  adsyntrix kamal-test-secrets)

# # Exporting the variables (they will be set, even if the result from 'extract' is an empty string)
# DB_HOST=$(kamal secrets extract DB_HOST $SECRETS_PAYLOAD)
# SECRET_KEY=$(kamal secrets extract SECRET_KEY $SECRETS_PAYLOAD)